import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import BottomTabs from "@/components/Bottomtabs";
import { Alert, Box, Flex, Text } from "@chakra-ui/react";
import { LuAlarmCheck, LuAlertCircle } from "react-icons/lu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Box my="2" mx="3">
            <Flex justifyContent="space-between">
              <Box>
                <Text fontSize="xl" color="green.500">
                  같이가치
                </Text>
              </Box>
              <Box>
                <Text fontSize="xl" color="green.500">
                  <LuAlertCircle />
                </Text>
              </Box>
            </Flex>
          </Box>
          {children}
          <BottomTabs />{" "}
        </Provider>
      </body>
    </html>
  );
}
